services:
  - type: web
    name: youtube-transcription
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_PROJECT_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true 