services:
  - type: web
    name: youtube-transcription
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      # Supabase variables removed (no database usage)
    healthCheckPath: /health
    autoDeploy: true 